name: Sonarcloud Scan

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Adding Summary
        run: | 
          echo "### ANALYSIS SUCCESSFUL" >> $GITHUB_STEP_SUMMARY
          echo "You can find the results [here](https://sonarcloud.io/dashboard?id=Mathmagicians_sonarqube&branch=master&resolved=false)" >> $GITHUB_STEP_SUMMARY